version: "3.7"
services:
    nginx:
        build:
            context: docker/nginx
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./:/app
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: docker/php-fpm
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        environment:
            DB_HOST: db
            DB_NAME: my_project
            DB_USER: webshake
            DB_PASSWORD: ${MYSQL_PASSWORD}

            MAILER_USER: ${MAILER_USER}
            MAILER_PASSWORD: ${MAILER_PASSWORD}
            MAILER_FROM_EMAIL: mail@app.test

            FRONTEND_URL: http://localhost:8080
        depends_on:
            - db

    db:
        image: mysql:5.7.22

        environment:
            MYSQL_DATABASE: my_project
            MYSQL_USER: webshake
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
            - ./data:/app
volumes:
    dbdata:


